CREATE TABLE IF NOT EXISTS T_COMMENT (
  ID      BIGINT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CONTENT LONGTEXT NOT NULL,
  CREATED DATETIME,
  USER_ID BIGINT   NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES T_USER (ID)
);