CREATE TABLE IF NOT EXISTS T_ITEM (
  ID            BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME          VARCHAR(50)   NOT NULL,
  DESCRIPTION   LONGTEXT      NOT NULL,
  UNIQUE_NUMBER VARCHAR(10),
  PRICE         NUMERIC(6, 2) NOT NULL
);