CREATE TABLE IF NOT EXISTS T_NEWS (
  ID      BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITLE   VARCHAR(30) NOT NULL,
  CONTENT TEXT        NOT NULL,
  CREATED DATETIME,
  USER_ID BIGINT      NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES T_USER (ID)
);