CREATE TABLE IF NOT EXISTS T_ROLE_PERMISSION (
  ROLE_ID       BIGINT NOT NULL,
  PERMISSION_ID BIGINT NOT NULL,
  PRIMARY KEY (ROLE_ID, PERMISSION_ID),
  KEY PERMISSION_ID(PERMISSION_ID),
  FOREIGN KEY (ROLE_ID) REFERENCES T_ROLE (ID),
  FOREIGN KEY (PERMISSION_ID) REFERENCES T_PERMISSION (ID)
);